apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: endpoint-slice-demo
  labels:
    kubernetes.io/endpoint-slice-demo: endpoint-slice-demo
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      -"172.31.2.237"
    conditions:
      ready: true
      hostname: pod-1
      nodeName: node-1
      zone: us-west2-a